### ISSUE TITLE
I get error everytime i try to download a file

### ISSUE THREAD

**Issue by duddy223** [Foxite/PatreonDownloader#2]
whenever i start to download a post, it says:   System.ArgumentNullException: Value cannot be null. (Parameter 'html')
   at HtmlAgilityPack.HtmlDocument.LoadHtml(String html)
   at PatreonDownloader.Program.DownloadMedia(HttpClient client, CookieContainer cookies, List`1 posts) in E:\Development\PatreonDownloader\PatreonDownloader\Program.cs:line 167
   at PatreonDownloader.Program.Main(String[] args) in E:\Development\PatreonDownloader\PatreonDownloader\Program.cs:line 83

can you msg me on discord with a potential fix? Duddy#0028

**Comment by Foxite** [comment]
I think what happened here is that it found a post that doesn't have any text content, and apparently the content property is null in those cases, as opposed to an empty string.

I've released an update, it shouldn't crash anymore. Please try this and close the issue if no more issues appear.

**Comment by duddy223** [comment]
i will try it now

**Comment by duddy223** [comment]
worked!
thanks
